Fixed git-prune to better deal with non-existing local branches.

diff --git a/bin/git-prune b/bin/git-prune
--- a/bin/git-prune
+++ b/bin/git-prune
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-myversion="1.0.0"
+myversion="1.0.1"
 myname=$(basename $0)
 mp="${myname}:"
 
@@ -42,38 +42,43 @@ fi
 prunable_branches=$(git remote show $remote \
                     | grep -E "use .git remote prune. to remove" \
                     | sed -e "s! *refs/remotes/${remote}/\([^ ]\+\) .*!\1 !g")
+local_branches=$(git branch --no-color |cut -c 3- |cut -d ' ' -f 1)
+remote_branches=$(git branch -r --no-color |cut -c 3- |cut -d ' ' -f 1)
 
 #echo "Debug: prunable_branches=<${prunable_branches}>"
+#echo "Debug: local_branches=<${local_branches}>"
+#echo "Debug: remote_branches=<${remote_branches}>"
 
 if [[ -n $prunable_branches ]]; then
 
-  for branch in $prunable_branches; do
-    if [[ $branch == $current_branch ]]; then
-      echo $mp "Error: Cannot prune branch that is checked out: $branch"
+  for lbranch in $prunable_branches; do
+    if [[ $lbranch == $current_branch ]]; then
+      echo $mp "Error: Pruneable branch is checked out: $lbranch"
       exit 1
     fi
   done
 
-  for branch in $prunable_branches; do
+  for lbranch in $prunable_branches; do
 
-    echo $mp "Pruning branch: $branch"
-
-    cmd="git branch -d $branch"
-    echo $cmd
-    $cmd
-    rc=$?
-    if [[ $rc != 0 ]]; then
-      echo $mp "Warning: git returns rc=$rc for: $cmd"
-      exit 1
+    if [[ $local_branches =~ $lbranch ]]; then 
+      #echo $mp "Deleting branch: $lbranch"
+      cmd="git branch -D $lbranch"
+      $cmd
+      rc=$?
+      if [[ $rc != 0 ]]; then
+        echo $mp "Warning: git returns rc=$rc for: $cmd"
+      fi
     fi
 
-    cmd="git branch -d -r $remote/$branch"
-    echo $cmd
-    $cmd
-    rc=$?
-    if [[ $rc != 0 ]]; then
-      echo $mp "Warning: git returns rc=$rc for: $cmd"
-      exit 1
+    rbranch=$remote/$lbranch
+    if [[ $remote_branches =~ $rbranch ]]; then 
+      #echo $mp "Deleting branch: $rbranch"
+      cmd="git branch -D -r $rbranch"
+      $cmd
+      rc=$?
+      if [[ $rc != 0 ]]; then
+        echo $mp "Warning: git returns rc=$rc for: $cmd"
+      fi
     fi
 
   done
